### ISSUE TITLE
Missing folder

### ISSUE THREAD

**Issue by Ahmadmustapha1** [SandeepReddy097/Brain-Tumor-Detection-and-Classification#1]
Thanks for the code, the follwing files are missing 1.raw_mri, 2.train_binary, 3.train_tumor_detected, 4.input, 5.test_sample, 6.test.binary and 7.test_tumor_detected.
Will you mind to share.
Thank you in anticipation.

**Comment by Ahmadmustapha1** [comment]
****

**Comment by Sudershhh** [comment]
> Thanks for the code, the follwing files are missing 1.raw_mri, 2.train_binary, 3.train_tumor_detected, 4.input, 5.test_sample, 6.test.binary and 7.test_tumor_detected.
> Will you mind to share.
> Thank you in anticipation.

I'm also facing the same issue. It would be really helpful if you could provide those missing folders.
